1.a)Lx=b

In [18]:
import numpy as np
n=7
rng=np.random.default_rng()
A=np.array(rng.integers(1,40,size=(n,n)))
b=np.array(rng.integers(2,70,size=n))
x = np.zeros((n,1))
L=np.tril(A)
for i in range(n):
    s=b[i]
    for j in range(i-2):
        s=s=L[i,j]*x[j]
    x[i]=s/L[i,i]
print(x)

[[ 5.77777778]
 [ 3.5       ]
 [ 0.80952381]
 [ 1.92592593]
 [ 9.        ]
 [ 0.14991182]
 [12.19753086]]


1.b)Ux=b

In [13]:
import numpy as np
n=7
rng=np.random.default_rng()
A=np.array(rng.integers(2,40,size=(n,n)))
b=np.array(rng.integers(2,70,size=(n,1)))
U=np.triu(A)
x = np.zeros((n,1))
for i in range(n-1,-1,-1):
    s=b[i]
    for j in range(i+1,n):
        s=s=U[i,j]*x[j]
    x[i]=s/U[i,i]
print(x)

[[ 0.625     ]
 [ 1.92857143]
 [ 1.10526316]
 [10.125     ]
 [ 0.51724138]
 [ 0.07258065]
 [ 0.75      ]]


2.G

In [135]:
import numpy as np
n=7
rng=np.random.default_rng()
A=np.array(rng.integers(2,40,size=(n,n)))
u=np.zeros((n,n))
print(np.triu(A))
for k in range(n-1):
    for i in range(k+1 , n):
        A[i, k] = u[i, k] = A[i, k] / A[k, k]   
    for i in range(k+1 , n):
        for j in range(k + 1, n):
            A[i, j] -= u[i, k]*A[k, j]


print(A)


[[36 28 35 13 39 27 15]
 [ 0 36 22  4  5 33  8]
 [ 0  0 16 12 22 23 21]
 [ 0  0  0 20 14 17  5]
 [ 0  0  0  0 21 39  4]
 [ 0  0  0  0  0 14 16]
 [ 0  0  0  0  0  0  9]]
[[ 36  28  35  13  39  27  15]
 [  0  34  20   3   2  31   7]
 [  0   0 -11   2  -2  -4   8]
 [  1   0   1   4 -19  14 -18]
 [  0   0   2  -1 -33  38 -51]
 [  0   0   1   0   0  -6   2]
 [  0   0   1   3  -2  -5 -65]]


GPP

In [ ]:
import numpy as np
n=7
rng=np.random.default_rng()
A=np.array(rng.integers(2,40,size=(n,n)))
u=np.zeros((n,n))
for k in range(1,n-1):
    