1.a)Lx=b

In [18]:
import numpy as np
n=7
rng=np.random.default_rng()
A=np.array(rng.integers(1,40,size=(n,n)))
b=np.array(rng.integers(2,70,size=n))
x = np.zeros((n,1))
L=np.tril(A)
for i in range(n):
    s=b[i]
    for j in range(i-2):
        s=s=L[i,j]*x[j]
    x[i]=s/L[i,i]
print(x)

[[ 5.77777778]
 [ 3.5       ]
 [ 0.80952381]
 [ 1.92592593]
 [ 9.        ]
 [ 0.14991182]
 [12.19753086]]


1.b)Ux=b

In [13]:
import numpy as np
n=7
rng=np.random.default_rng()
A=np.array(rng.integers(2,40,size=(n,n)))
b=np.array(rng.integers(2,70,size=(n,1)))
U=np.triu(A)
x = np.zeros((n,1))
for i in range(n-1,-1,-1):
    s=b[i]
    for j in range(i+1,n):
        s=s=U[i,j]*x[j]
    x[i]=s/U[i,i]
print(x)

[[ 0.625     ]
 [ 1.92857143]
 [ 1.10526316]
 [10.125     ]
 [ 0.51724138]
 [ 0.07258065]
 [ 0.75      ]]


2.G

In [1]:
import numpy as np
n=7
rng=np.random.default_rng()
A=np.array(rng.integers(2,40,size=(n,n)))
b=np.array(rng.integers(2,70,size=n))
u=np.zeros((n,n))
print('-----------A------------')
print(A)
print('-----------b------------')
print(b)
print("Solution:", np.linalg.inv(A)@b)
def Utris(U,b):
    n = U.shape[0]
    x = np.zeros((n,1))
    for i in range(n-1,-1, -1):
        s = b[i]
        for j in range(i+1,n):
            s =s - U[i][j]*x[j]
        x[i] = s/U[i][i]
    return x

for k in range(n-1):
    for i in range(k+1 , n):
        A[i, k]= A[i, k] / A[k, k]   
    for i in range(k+1 , n):
        for j in range(k + 1, n):
            A[i, j] -= A[i, k]*A[k, j]
A=np.triu(A)
print(Utris(A,b))



-----------A------------
[[31 31 26 32  4 23 15]
 [28  6 13  8 30  3 15]
 [24 17 16 14 11 34 27]
 [22 15  8 23 34 34 21]
 [24 31 34 31 17 38 39]
 [10 25 23 28 10 38  3]
 [20  4 21 38 28  3 37]]
-----------b------------
[27 19 38 27 16 52 58]
Solution: [ 1.95613362 -5.8301572   2.44846147  1.79670037 -1.0531866   2.27759348
 -1.48210552]
[[ -1.7097135 ]
 [-33.89168057]
 [ 20.63521215]
 [ 20.74759948]
 [ -6.92038738]
 [ -1.89185423]
 [  0.09324759]]


GPP