1.a)Lx=b

In [18]:
import numpy as np
n=7
rng=np.random.default_rng()
A=np.array(rng.integers(1,40,size=(n,n)))
b=np.array(rng.integers(2,70,size=n))
x = np.zeros((n,1))
L=np.tril(A)
for i in range(n):
    s=b[i]
    for j in range(i-2):
        s=s=L[i,j]*x[j]
    x[i]=s/L[i,i]
print(x)

[[ 5.77777778]
 [ 3.5       ]
 [ 0.80952381]
 [ 1.92592593]
 [ 9.        ]
 [ 0.14991182]
 [12.19753086]]


1.b)Ux=b

In [13]:
import numpy as np
n=7
rng=np.random.default_rng()
A=np.array(rng.integers(2,40,size=(n,n)))
b=np.array(rng.integers(2,70,size=(n,1)))
U=np.triu(A)
x = np.zeros((n,1))
for i in range(n-1,-1,-1):
    s=b[i]
    for j in range(i+1,n):
        s=s=U[i,j]*x[j]
    x[i]=s/U[i,i]
print(x)

[[ 0.625     ]
 [ 1.92857143]
 [ 1.10526316]
 [10.125     ]
 [ 0.51724138]
 [ 0.07258065]
 [ 0.75      ]]


2.G

In [21]:
import numpy as np
n=7
rng=np.random.default_rng()
A=np.array(rng.integers(2,40,size=(n,n)))
b=np.array(rng.integers(2,70,size=n))
u=np.zeros((n,n))
print('-----------A------------')
print(A)
print('-----------b------------')
print(b)
print("Solution:", np.linalg.inv(A)@b)
def Utris(U,b):
    n = U.shape[0]
    x = np.zeros((n,1))
    for i in range(n-1,-1, -1):
        s = b[i]
        for j in range(i+1,n):
            s =s - U[i][j]*x[j]
        x[i] = s/U[i][i]
    return x

for k in range(n-1):
    for i in range(k+1 , n):
        A[i, k]= A[i, k] / A[k, k]   
    for i in range(k+1 , n):
        for j in range(k + 1, n):
            A[i, j] -= A[i, k]*A[k, j]
A=np.triu(A)
print(Utris(A,b))



-----------A------------
[[ 3  5 30 18 37 35 16]
 [ 3 33 32 29 22 31 38]
 [28 19  3 17 11 19  4]
 [ 5 13 30 19 33 33 27]
 [11  5 11  8 24 30 24]
 [12 24 10 11 12  7 19]
 [38  3 12 12 29 24 30]]
-----------b------------
[38 50 15 53 51 61 37]
Solution: [ 0.18042662  3.21138461  0.72035    -4.97186898  1.78696972  0.57015003
  0.20073798]
[[ 12.73601948]
 [-18.04283268]
 [-27.60552444]
 [ 55.81325597]
 [ -0.29872289]
 [ -1.83554889]
 [ -0.69811321]]


GPP