In [1]:
# Nume Student:
# Factorizarea LU. Rezolvarea sistemului Ax = b

import numpy as np

rng = np.random.default_rng(0)
# ----------------- Input  -----------------------------------
#   !!!! Aceasta sectiune nu se modifica !!!!
n = 5;
A = np.diagflat(rng.integers(1,10, size=(n,1)), k=0)
A[:, n-1] = rng.integers(1,20, size=(1,n))
A[:, 0] = rng.integers(1,20, size=(1,n))
for i  in range (0,n-1):
    A[i+1,i] = rng.integers(1,10, size=(1,1))

b = rng.integers(1,10, size=(n,1)).astype(float)
#-----------------------------------------------------
print('-------------A------------------')
print(A)
print('-----------b--------------------')
print(b)

sol = np.linalg.inv(np.copy(A))@np.copy(b)

def Crout(A):
    n = len(A)
    U = np.zeros((n,n))
    L = np.zeros((n,n))
    for i in range (0,n):
        L[i][0] = A[i][0]
    U[0][n-1] = A[0][n-1]/L[0][0]
    for k in range (1,n-1):
        L[k][k] = A[k][k];
        L[k+1][k] = A[k+1][k]
    L[n-1][n-1] = A[n-1][n-1]-L[n-1][0]*U[0][n-1]-L[n-1][n-2]*U[n-2][n-1]
    L[n-1][n-2] = A[n-1][n-2]

    for i in range (0,n):
        U[i][i] = 1
    U[1][n-1] = (A[1][n-1]-L[1][0]*U[0][n-1])/L[1][1]
    for i in range(2,n-1):
        U[i][n-1] = (A[i][n-1]-L[i][0]*U[0][n-1]-L[i][n-i]*U[i-1][n-1])/L[i][i]
    return L, U

[L, U] = Crout(A)
print('----------- L ---------------')
print(L)
print('----------- U ---------------')
print(U)
print('----------- Check LU = ---------------')
print(L @ U)

def LTRIS(L,b):
        n = len(L)
        y = np.zeros((n,1))
        for i in range(n):
            y[i]=b[i]
        for i in range(n):
            y[i]=L[i][0]*y[0]+L[i][i-1]*y[i-1]
            y[i]/=L[i][i]
        return y

def UTRIS(U,y):
    n = len(U)
    x = np.zeros((n,1))
    for i in range(n-2,0,-1):
        x[i] = y[1]
    for i in range(i+1,n):
        x[i] = U[i][0]*x[i]*x[1]+U[i][i-1]*x[i-1]
        x[i]/=U[1][1]

    return x

y =LTRIS(L,b)
x = UTRIS(U,y)

print('----------x------------')
print(x)

print('------------sol----------')
print(sol)
print('L*U == ')
print(L@U)

-------------A------------------
[[13  0  0  0  1]
 [ 7  6  0  0  2]
 [10  6  5  0  1]
 [12  0  5  3  4]
 [19  0  0  6 16]]
-----------b--------------------
[[9.]
 [3.]
 [8.]
 [7.]
 [1.]]
----------- L ---------------
[[13.          0.          0.          0.          0.        ]
 [ 7.          6.          0.          0.          0.        ]
 [10.          6.          5.          0.          0.        ]
 [12.          0.          5.          3.          0.        ]
 [19.          0.          0.          6.         14.53846154]]
----------- U ---------------
[[1.         0.         0.         0.         0.07692308]
 [0.         1.         0.         0.         0.24358974]
 [0.         0.         1.         0.         0.04615385]
 [0.         0.         0.         1.         0.94871795]
 [0.         0.         0.         0.         1.        ]]
----------- Check LU = ---------------
[[13.          0.          0.          0.          1.        ]
 [ 7.          6.          0.          0.  

C:\Users\cosmi\AppData\Local\Temp\ipykernel_20424\43650066.py:14: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  A[i+1,i] = rng.integers(1,10, size=(1,1))
