In [9]:
#Nume student:
#############################
#           Factorizarea LU
#    Rezolvarea sistemului Ax =b
#############################

import numpy as np

rng = np.random.default_rng(0) #generator

#------------ Input --------------------------------
#   !!!Aceasta sectiune nu se modifica!!!
n = 5;
A = np.diagflat(rng.integers(1,10, size=(n,1)), k=0)
A[n-1,:] = rng.integers(1,20, size=(1,n))
A[0,:] = rng.integers(1,20, size=(1,n))
A = A.astype(float);
b = rng.integers(1,10, size=(n,1)).astype(float)
#-----------------------------------------------------

print('-------------A------------------')
print(A)
print('-----------b--------------------')
print(b)
#Pentru verificarea solutiei
sol = np.linalg.inv(np.copy(A))@np.copy(b)

# ------Factorizarea LU-------
def Crout(A):
    n = len(A)
    U = np.zeros((n,n))
    L = np.zeros((n,n))
    for i in range(0,n):
         U[i][i] = 1
    L[0][0] = A[0][0]
    L[n-1][0] = A[n-1][0]
    for j in range(1,n):
         U[0][j] = A[0][j]/L[0][0]
    for k in range(1,n):
        for i in range(k,n):
            sum=0
            for l in range(1,k-1):
                sum+=L[i][l]*U[l][k]
            L[i][k] =A[i][k]-sum
            if(k==n):
                break
            for j in range(k+1,n):
                sum=0
                for l in range(1,k-1):
                    sum+=L[k][l]*U[l][j]
                U[k][j]=(A[k][j]-sum)/L[k][k]
        
    return L, U

#----------- LTRIS ------------
def LTRIS(L,b):
    n = len(L)
    y = np.zeros((n,1))
    
    return y

#----------- UTRIS ------------
def UTRIS(U,y):
    n = len(U)
    x = np.zeros((n,1))
    
    return x

[L, U] = Crout(np.copy(A))
print('----------- L ---------------')
print(L)
print('----------- U ---------------')
print(U)

#Verificarea factorizarii LU 
print('----------- A_obt---------------')
print(L @ U)

y =LTRIS(L,b)
x = UTRIS(U,y)

print('----------x------------')
print(x)
#Verificarea finala
print('------------sol----------')
print(sol)




-------------A------------------
[[13. 18. 10. 12. 19.]
 [ 0.  6.  0.  0.  0.]
 [ 0.  0.  5.  0.  0.]
 [ 0.  0.  0.  3.  0.]
 [ 1.  2.  1.  4. 16.]]
-----------b--------------------
[[7.]
 [6.]
 [5.]
 [6.]
 [9.]]
----------- L ---------------
[[13.          0.          0.          0.          0.        ]
 [ 0.          6.          0.          0.          0.        ]
 [ 0.          0.          5.          0.          0.        ]
 [ 0.          0.          0.          3.          0.        ]
 [ 1.          0.61538462  0.23076923  3.07692308 14.53846154]]
----------- U ---------------
[[1.         1.38461538 0.76923077 0.92307692 1.46153846]
 [0.         1.         0.         0.         0.        ]
 [0.         0.         1.         0.         0.        ]
 [0.         0.         0.         1.         0.        ]
 [0.         0.         0.         0.         1.        ]]
----------- A_obt---------------
[[13. 18. 10. 12. 19.]
 [ 0.  6.  0.  0.  0.]
 [ 0.  0.  5.  0.  0.]
 [ 0.  0.  0.  3. 