In [3]:
#Nume student:
#############################
#           Factorizarea LU
#    Rezolvarea sistemului Ax =b
#############################

import numpy as np

rng = np.random.default_rng(0) #generator

#------------ Input --------------------------------
#   !!!Aceasta sectiune nu se modifica!!!
n = 5;
A = np.diagflat(rng.integers(1,10, size=(n,1)), k=0)
A[n-1,:] = rng.integers(1,20, size=(1,n))
A[0,:] = rng.integers(1,20, size=(1,n))
A = A.astype(float);
b = rng.integers(1,10, size=(n,1)).astype(float)
#-----------------------------------------------------

print('-------------A------------------')
print(A)
print('-----------b--------------------')
print(b)
#Pentru verificarea solutiei
sol = np.linalg.inv(np.copy(A))@np.copy(b)

# ------Factorizarea LU-------
def Crout(A):
    n = len(A)
    U = np.zeros((n,n))
    L = np.zeros((n,n))
    
    return L, U

#----------- LTRIS ------------
def LTRIS(L,b):
    n = len(L)
    y = np.zeros((n,1))
    
    return y

#----------- UTRIS ------------
def UTRIS(U,y):
    n = len(U)
    x = np.zeros((n,1))
    
    return x

[L, U] = Crout(np.copy(A))
print('----------- L ---------------')
print(L)
print('----------- U ---------------')
print(U)

#Verificarea factorizarii LU 
print('----------- A_obt---------------')
print(L @ U)

y =LTRIS(L,b)
x = UTRIS(U,y)

print('----------x------------')
print(x)
#Verificarea finala
print('------------sol----------')
print(sol)




-------------A------------------
[[13.  0.  0.  0.  1.]
 [18.  6.  0.  0.  2.]
 [10.  0.  5.  0.  1.]
 [12.  0.  0.  3.  4.]
 [19.  0.  0.  0. 16.]]
-----------b--------------------
[[7.]
 [6.]
 [5.]
 [6.]
 [9.]]
----------- L ---------------
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
----------- U ---------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
----------- A ---------------
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
----------x------------
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
------------sol----------
[[ 0.54497354]
 [-0.60670194]
 [-0.07301587]
 [-0.0670194 ]
 [-0.08465608]]
