In [5]:
# Nume student:
# CMMP - Problema celor mai mici patrate
# TORT - triangularizare ortogonala cu reflectori 
import numpy as np
rng = np.random.default_rng(0)

# ----------- Input ---------------------------
#  !! Sectiunea Input nu se modifica !!
m = 7 # nr de linii
n = 4 # nr de coloane
A = rng.integers(1,11, size=(m,n))
A = np.triu(A,-1)
A[m-1,:] = rng.integers(1,10, size=(1,n))
A = A.astype(float)
b = rng.integers(10, size=(m,1)).astype(float)
#-----------------------------------------------
print('------------A-------------\n', A)

sol = np.linalg.pinv(np.copy(A))@np.copy(b)

# Descompunerea QR comanda in Python
q,r = np.linalg.qr(np.copy(A))
print('--------q-----\n', q)
print('--------r-----\n',r)

def  TORT (A):
    m,n  = np.shape(A)
    U = np.zeros((m,n))
    p = min(m-1,n)
    beta = np.zeros((p,1))
    for k in range(p):
        # Calcularea lui sigma
        s = A[k+1][k]**2 +A[m-1][k]**2 + A[k][k]**2 #nu mai avem nevoie de for pentru suma
        sigma = np.sign(A[k,k])*np.sqrt(s)
        if sigma != 0:
            # Calcularea vectorilor householder
            U[k][k] = A[k][k] +sigma
            U[k+1][k] = A[k+1][k]#restul elementelor sunt nule
            U[m-1][k] = A[m-1][k]          
            beta[k] = sigma*U[k,k]
            #Aplicarea reflectorului Householder pe A
            for j in range(k,n):
                tau = U[k][k]*A[k][j] + U[k+1][k]*A[k+1][j] + U[m-1][k]*A[m-1][j]
                tau =tau/beta[k]
                A[k,j]=A[k,j]-tau*U[k,k]
                A[k+1,j]=A[k+1,j]-tau*U[k+1,k]
                A[m-1,j]=A[m-1,j]-tau*U[m-1,k]
                    
    return U, A, beta

# Algoritmul UTRIS
def Utris(U, b):
    n = len(U)
    x = np.zeros((n,1))
    for i in range(n-1,-1, -1):
        s = b[i]
        for j in range(i+1,n):
            s = s -U[i][j]*x[j]
        x[i] = s/U[i][i]
    return x


#Triangularizarea ortogonala a lui A
U,R,beta  = TORT(A)
print('----------U------------\n', U)
print('-----------R-----------\n',R)

# Aplicarea Reflectorilor asupra lui b
for k in range(n):
    tau = U[k][k]*b[k] + U[k+1][k]*b[k+1]+ U[m-1][k]*b[m-1]
    tau = tau/beta[k]
    b[k]= b[k]- tau*U[k][k]
    b[m-1] = b[m-1] - tau*U[m-1][k]
    b[k+1] = b[k+1] - tau*U[k+1][k]

#Calcularea solutiei CMMP
x  =Utris(R[0:n,:], b[0:n,0])

print('-----------x------------\n',x)
print('----------sol------------\n', sol)

------------A-------------
 [[ 9.  7.  6.  3.]
 [ 4.  1.  1.  1.]
 [ 0.  9.  7. 10.]
 [ 0.  0. 10.  8.]
 [ 0.  0.  0. 10.]
 [ 0.  0.  0.  0.]
 [ 7.  7.  8.  2.]]
--------q-----
 [[-0.7448453  -0.01607809 -0.08919961 -0.09840737]
 [-0.33104236 -0.23240151 -0.03471436 -0.21176765]
 [-0.          0.96030056 -0.03139359 -0.09245752]
 [-0.          0.          0.98577716 -0.05308563]
 [-0.          0.          0.         -0.93425423]
 [-0.          0.          0.          0.        ]
 [-0.57932412  0.15347269  0.13452199  0.24753385]]
--------r-----
 [[-12.08304597  -9.60022831  -9.43470713  -3.7242265 ]
 [  0.           9.37206575   7.62101541   9.62931522]
 [  0.           0.          10.14428043   7.53901221]
 [  0.           0.           0.         -10.7037246 ]]
----------U------------
 [[ 21.08304597   0.           0.           0.        ]
 [  4.         -11.52155911   0.           0.        ]
 [  0.           9.         -10.60372338   0.        ]
 [  0.           0.          10.     

C:\Users\cosmi\AppData\Local\Temp\ipykernel_11472\550277335.py:47: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  A[i,j] = A[i, j] - tau *U[i,k]
